export const IndustIdList = [
  {id: 1, name: 'A 农、林、牧、渔业'},
  {id: 2, name: 'B 采矿业'},
  {id: 3, name: 'C 制造业'},
  {id: 4, name: 'D 电力、热力、燃气及水生产和供应业'},
  {id: 5, name: 'E 建筑业'},
  {id: 6, name: 'F 批发和零售业'},
  {id: 7, name: 'G 交通运输、仓储和邮政业'},
  {id: 8, name: 'H 住宿和餐饮业'},
  {id: 9, name: 'I 信息传输、软件和信息技术服务业'},
  {id: 10, name: 'J 金融业'},
  {id: 11, name: 'K 房地产业'},
  {id: 12, name: 'L 租赁和商务服务业'},
  {id: 13, name: 'M 科学研究和技术服务业'},
  {id: 14, name: 'N 水利、环境和公共设施管理业'},
  {id: 15, name: 'O 居民服务、修理和其他服务业'},
  {id: 16, name: 'P 教育'},
  {id: 17, name: 'Q 卫生和社会工作'},
  {id: 18, name: 'R 文化、体育和娱乐业'},
  {id: 19, name: 'S 公共管理、社会保障和社会组织'},
  {id: 20, name: 'T 国际组织'},
  {id: 21, name: '其他'},
];
